	PROGRAM-ID.A.DATA DIVISION.LOCAL-STORAGE SECTION. 1 L PIC X(51).
	1 T PIC X(51). 1 I PIC 99. 1 K PIC 9. PROCEDURE DIVISION.A.
	ACCEPT L.MOVE 1 TO I.B.IF"T"=L(I:1)MOVE L TO T.IF"K"=L(I:1)MOVE
	1 TO K.IF K=1 IF"T"=T(I:1)DISPLAY T STOP RUN ELSE MOVE"K"TO T(I:
	1).ADD 1 TO I.IF I<51 GO TO B.DISPLAY T.GO TO A.